[package]
name = "ray-tracing-weekend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.86"
indicatif = { version = "*", features = ["rayon"] }
rand = "0.8.5"
rayon = "1.10.0"
